In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\tomas\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
print(a_list)
print(a_list[1][1])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
6


In [6]:
a_np = np.array( [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)
print(a_np)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
import numpy as np


In [ ]:
#1D array

In [7]:
array_1d = np.array([1,5,7,9,71,14])

In [9]:
print (array_1d.shape)
print(len(array_1d))

(6,)
6


In [10]:
print (array_1d)

[ 1  5  7  9 71 14]


In [ ]:
#3d

In [11]:
np.random.rand(2,5,3)

array([[[0.87625495, 0.17481024, 0.93750951],
        [0.03234952, 0.74606274, 0.47398633],
        [0.69133427, 0.15450705, 0.04056673],
        [0.29820544, 0.77863922, 0.22232887],
        [0.94884405, 0.86927311, 0.08175096]],

       [[0.37809442, 0.96505059, 0.5894279 ],
        [0.05457696, 0.31656378, 0.81584292],
        [0.79402108, 0.30354569, 0.956724  ],
        [0.68603256, 0.35784291, 0.07774676],
        [0.36563097, 0.70711148, 0.94609491]]])

In [12]:
#numby operations


In [13]:
py_list = [1,2,3,4,5]
print (py_list * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [14]:
np_array = np.array ([1,2,3,4,5])

In [15]:
print(np_array * 3)

[ 3  6  9 12 15]


In [16]:
print(np_array / 3)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [17]:
#Numby speed


In [18]:
size = 100000

In [19]:
py_list = list(range(size))

In [20]:
np_arr = np.arrange(size)

AttributeError: module 'numpy' has no attribute 'arrange'